#!/usr/bin/env python
import os
import subprocess


def make_if_not_exist(path):
    if not os.path.exists(path):
        os.mkdir(path)

def ssh_keygen():
    while True:
        i = raw_input("Do you want to generate new SSH key? (y/n) ")
        if i == 'y':
            ssh_dir = os.path.join(os.getenv('HOME'), '.ssh')
            key = os.path.join(ssh_dir, 'github')
            make_if_not_exist(ssh_dir)
            subprocess.call(['ssh-keygen', '-t', 'rsa', '-f', key])
            print(open(key + '.pub').read())
            break
        if i == 'n':
            break

def clone_config_script():
    repo = os.path.join(os.getenv('HOME'), 'repo')
    config_script = os.path.join(repo, 'config_script')
    make_if_not_exist(repo)
    subprocess.call([ 'git', 'clone', 'https://github.com/sgkim126/config_script.git', config_script ])


if __name__ == '__main__':
    ssh_keygen()
    clone_config_script()
