# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]
then
    debian_chroot=$(cat /etc/debian_chroot)
fi

source ~/.bash_color

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias vi='vim'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

export EDITOR=/usr/bin/vim

export LANG='ko_KR.UTF-8'
export LC_ADDRESS='ko_KR.UTF-8'
export LC_IDENTIFICATION='ko_KR.UTF-8'
export LC_MEASUREMENT='ko_KR.UTF-8'
export LC_MONETARY='ko_KR.UTF-8'
export LC_NAME='ko_KR.UTF-8'
export LC_NUMERIC='ko_KR.UTF-8'
export LC_PAPER='ko_KR.UTF-8'
export LC_TELEPHONE='ko_KR.UTF-8'
export LC_TIME='ko_KR.UTF-8'
export MDM_LANG='ko_KR.UTF-8'

umask 022

# if the command-not-found package is installed, use it
if [ -x /usr/lib/command-not-found ]; then
    function command_not_found_handle {
        # check because c-n-f could've been removed in the meantime
        if [ -x /usr/lib/command-not-found ]; then
            /usr/bin/python /usr/lib/command-not-found -- $1
            return $?
        else
            return 127
        fi
    }
fi

if [ -f /etc/bash_completion ]
then
    source /etc/bash_completion
fi

if [ -f "$HOME/.rvm/scripts/rvm" ]
then
    source "$HOME/.rvm/scripts/rvm"
fi

[[ -s "$HOME/.rsvm/rsvm.sh" ]] && . "$HOME/.rsvm/rsvm.sh" # This loads RSVM

if [ -f "$HOME/.bash_local" ]
then
    source "$HOME/.bash_local"
fi

if [ $(which mate-screensaver-command) ]
then
    iwillworkfor() {
        echo "mate-screensaver-command --lock" | at now + $1 $2
    }
    iwillworkuntil() {
        echo "mate-screensaver-command --lock" | at $@
    }
elif [ $(which gnome-screensaver-command) ]
then
    iwillworkfor() {
        echo "gnome-screensaver-command --lock" | at now + $1 $2
    }
    iwillworkuntil() {
        echo "gnome-screensaver-command --lock" | at $@
    }
fi
# vim:set ft=sh:

# added by travis gem
[ -f /home/sgkim126/.travis/travis.sh ] && source /home/sgkim126/.travis/travis.sh
