if filereadable(expand("~/.vim/config/options.vim"))
    source ~/.vim/config/options.vim
endif

if filereadable(expand("~/.vim/config/keymaps.vim"))
    source ~/.vim/config/keymaps.vim
endif

filetype off

if filereadable(expand("~/.vim/plugins.vim"))
    source ~/.vim/plugins.vim
endif

filetype plugin indent on
