set all&

colorscheme elflord

set wrap

set history=100

vmap <Tab> >gv
vmap <S-Tab> <gv

imap <UP> <C-O>gk
imap <DOWN> <C-O>gj
map <UP> gk
map <DOWN> gj

" Resize windows
nnoremap <leader>+ :resize +4<CR>
nnoremap <leader>- :resize -4<CR>
nnoremap <leader>< :vertical resize -4<CR>
nnoremap <leader>> :vertical resize +4<CR>

set mps+=<:>

set nocompatible
set backspace=indent,eol,start
set startofline

set hlsearch
set incsearch
set nowrapscan

set wildmenu
set showcmd

set ruler
set nonumber

set swapfile
set nobackup
set undofile
set undodir=~/.vim/undo

set showmatch

set cindent
set smartindent

set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

set textwidth=119

filetype off

if filereadable(expand("\~/.vim/plugins.vim"))
    source \~/.vim/plugins.vim
endif

filetype plugin indent on
